services:
  bot:
    container_name: bot
    hostname: bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-bot
    env_file:
      - .env
    networks:
      - bbb-translation-bot
    ports:
      - 9090:8080
    depends_on:
      - changeset-service
      - transcription-service
      - translation-service

  changeset-service:
    container_name: changeset-service
    hostname: changeset-service
    restart: always
    build:
      context: https://github.com/bigbluebutton-bot/changeset-grpc.git
      dockerfile: Dockerfile
    networks:
      - bbb-translation-bot

  transcription-service:
    container_name: transcription-service
    hostname: transcription-service
    restart: always
    build:
      context: ./transcription-service
      dockerfile: Dockerfile.cpu
    networks:
      - bbb-translation-bot
    env_file:
      - .env
    volumes:
      - ./.models:/app/.models
      - /tmp:/tmp  
    ports:
      - "8001:8001"  # make sure port 8001 is exposed to match bot's health check
    healthcheck:
      test: ["CMD-SHELL", "python healthcheck.py || exit 1"]
      interval: 30s
      retries: 3

  translation-service:
    container_name: translation-service
    hostname: translation-service
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "5000:5000"   # internal port is 5000, bot will call transcription-service separately
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      retries: 5
    command: ["--ssl", "--ga-id", "MY-GA-ID"]
    volumes:
      - ./.models/libretranslate:/root/.local:rw
    networks:
      - bbb-translation-bot

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: always
    ports:
      - 1000:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bbb-translation-bot

networks:
  bbb-translation-bot:
    driver: bridge

